# Generated by Django 4.1.6 on 2023-04-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0004_alter_watchlist_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['bid_amount']},
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='winner',
            name='win_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
