# Generated by Django 4.1.6 on 2023-04-29 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_options_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
